
controllers:
    resource: ../src/Controller/
    type: attribute

course_routes:
    resource: '../src/Controller/CourseController.php'
    type: annotation

task_routes:
    resource: '../src/Controller/TaskController.php'
    type: annotation

user_routes:
    resource: '../src/Controller/UserController.php'
    type: annotation

app.swagger_ui:
  path: /theory-practise/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /theory-practise/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
