nelmio_api_doc:
  documentation:
    servers:
      - url: http://localhost:8000
        description: API over HTTP
      - url: https://xn--b1afb6bcb.xn--g1abp6e.xn----gtbbcb4bjf2ak.xn--p1ai
        description: API over HTTPS
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: apiKey
          name: Authorization
          in: header
    security:
      - Bearer: []
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/theory-practise(?!/doc$)
