nelmio_api_doc:
  documentation:
    servers:
      - url: https://back.lang.yourtar.ru
        description: API over HTTPS
      - url: http://localhost:8000
        description: API over HTTP
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: apiKey
          name: Authorization
          in: header
    security:
      - Bearer: []
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/api(?!/doc$)
